{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thunderdb.secretName" . }}
  labels:
    {{- include "thunderdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  THUNDERDB_SUPERUSER_PASSWORD_HASH: {{ .Values.credentials.superuserPasswordHash | quote }}
{{- end }}
